### ISSUE TITLE
Support for SpellVisualMap Setup/in Spell Editor

### ISSUE THREAD

**Issue by gnarbrok** [stoneharry/WoW-Spell-Editor#101]
**Is your feature request related to a problem? Please describe.**
The spell editor is very easy to set up and use, but using the spellvisualmapbuilder tool is a bit more difficult for those new to wow emulation. Making the spellvisualmapbuilder more intuitive to set up would be really great.

**Describe the solution you'd like**
The (probably impossible) ideal would be to see any spell effects in the spell editor, although that seems like at best an enormous amoutn of work and at worst impossible.

So just an easier setup would be nice, although, since I have obviously failed to get it working, what that looks like is not very clear to me. Clear locations for the requisite files might be helpful. Also maybe super-clear setup instructions (running the program) for dummies like me :)

Happy to talk more about what might be helpful in this regard.

**Any other comments/information**

**Comment by stoneharry** [comment]
You are right that adding a Spell visual renderer to the program would be a ton of work.

I can add the visual map builder to the spell editor quite easily. The only bit I'm not sure how to handle is generating the database queries, because the columns to insert into depends on the emulator and revision you are using. I guess I can make a template that can be modified.

**Comment by gnarbrok** [comment]
Well that sounds like something I could do, and like it would simplify things a lot.

It seems like if you are someone who wants to use the visual map builder, then you probably also at least have enough experience with emulation to fill out the template. (Although maybe I shouldn't say that before I've tried to get it working.)

But I think that is a great idea and would really appreciate a feature like that.

**Comment by stoneharry** [comment]
I've started working on this.

The UI can look something like this:
![screenshot](https://i.imgur.com/9kqHqmx.png)

These will be the templates and SPELLS folder it parses:
![config](https://i.imgur.com/NCykYEB.png)

The SPELLS folder is ~60MB, so quite a lot to distribute with the program for one feature. Ideally we would target the WoW directory and parse read the MPQs directly, but this requires quite a bit more work to support. So I'll go with distributing the SPELLS folder approach for now.

This is still not going to be the most user friendly tool. I'm not providing any way to revert the database queries should you not be happy with the config. I'm relying on the user being able to do this themselves.

**Comment by stoneharry** [comment]
@gnarbrok No promises on when this feature is going to be finished, but I'm making quite good progress at the moment with this whole quarantine thing.

Would you be able to alpha test it for me when it is ready? I don't have a emulator setup to test it - I have not actually opened WoW in years. If so, do you have Discord? :)

**Comment by gnarbrok** [comment]
Yes I do! Sorry to get back to this so late - I've been pretty distracted recently.
My discord is phronesis#0426. And I would be happy to test it!

**Comment by yun000** [comment]
I have created all the SQL files on my server
Now I enter the game and prompt me below：target map or coordinates is invalid
Do I need other patch files?

**Comment by stoneharry** [comment]
@yun000 How are you trying to get there? `.go xyz 0 0 - 10 13` should work.

**Comment by yun000** [comment]
I use WoW_Spell_Editor_v1_9_5

Creature.sql is such ///////insert into `creature` (`id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y `, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) values('150000','900','0','0','1','1','0','0','14000','14000','0','0', '30','0','0','100','0','0','0','0','0','0');

Im .go xyz 0 0 -10 13
Nothing there

**Comment by stoneharry** [comment]
@yun000 there's a few things you can check:
- If you look at the creature table and look for the entries you have inserted, is the data present and do the columns look like they have the right values?
- Is there any DB errors logged for the new npc ids?
- If you go to the ground on map 13 and try to do the `.npc near 100` command, are any returned?
- Have you updated the two required DBC files client side in a MPQ?

**Comment by yun000** [comment]
Yes, there are no errors in my database, I can use commands to add spell effects into the game
But I teleport to the coordinate position and there is no spell effect
Your Creature.sql MAP ID is 900
The .go xyz 0 0 -10 13 MAP ID is 13

**Comment by yun000** [comment]
Input .npc near 100
Get Found near creatures (distance 100.000000):0

**Comment by yun000** [comment]
![QQ图片20200618231600](https://user-images.githubusercontent.com/15007756/85038885-b4497300-b1b9-11ea-8a3d-3c65f37e8b43.png)

**Comment by yun000** [comment]
The data in your Creature.sql is wrong

**Comment by stoneharry** [comment]
I can see the columns you are inserting into don't match up with the values.

**Comment by yun000** [comment]
I download WoW_Spell_Editor_v1_9_5.exe
Get them after unzipping

**Comment by yun000** [comment]
I can be sure that Creature.sql is problematic
Can you give me a correct Creature.sql file?

**Comment by stoneharry** [comment]
Yes, as I've already said that is not kept up to date with emulator database changes.

**Comment by yun000** [comment]
The Creature.sql I got in D:\WoW Spell Editor\SpellVisualMapBuilder\Export
Did not add the NPC correctly

**Comment by stoneharry** [comment]
I cannot help further. Sorry.

**Comment by yun000** [comment]
Ok! It seems I have to fix it myself!
thank you

**Comment by stoneharry** [comment]
![Screenshot](https://i.imgur.com/DtEXCE6.png)

I've resumed working on this feature.

**Comment by stoneharry** [comment]
I ended up merging the code, I'll release a new version soon and close this issue upon release. If there are any issues with the new functionality then I can follow up with a fix in a subsequent release.

**Comment by stoneharry** [comment]
Published v1.9.6 which includes this new feature. Please feel free to report any issues you find testing it.

Closing this issue now.
