### ISSUE TITLE
SpellVisualID and VisualKit new entries creation

### ISSUE THREAD

**Issue by Aentium** [stoneharry/WoW-Spell-Editor#102]
**Currently, in order to make a new SpellVisualID you have to edit SpellVisual.dbc with WDBX Editor and add a row. Same with VisualKits.**
Solution: Add an option for creating new SpellVisual and VisualKits IDs.

**Comment by stoneharry** [comment]
It's not that user friendly, but you can already do this. If you copy an existing spell visual kit to a Spell without a visual, it will create a copy with new ids automatically.

Whenever you copy and paste visual kits it always creates it with a new id.

**Comment by Aentium** [comment]
It does. Thanks!

**Comment by stoneharry** [comment]
There's definitely some improvements that can be done to make it more user friendly, but there are a lot of other features I would like to work on first. 😄
