### ISSUE TITLE
Remember Import/Export Settings

### ISSUE THREAD

**Issue by tikki100** [stoneharry/WoW-Spell-Editor#104]
**Default behaviour**
Currently, when clicking Import/Export, this opens a new window choosing improt by default. If you want to export, you can move to the export tab where a few DBC's are preselected. From here you can export. This resets everytime you need to export.

**Suggested behaviour**
Remember the last settings. If you choose to export only Spell.DBC last time, open up the same page with the same DBC's ticked :)

**Comment by stoneharry** [comment]
This has been greatly improved under #208 and release build v.2.1.2 -- I think this can be closed.
