### ISSUE TITLE
Bindings goes beyond frame

### ISSUE THREAD

**Issue by tikki100** [stoneharry/WoW-Spell-Editor#108]
**Spell editor version**
65ef64d665e0fb163cffb9b2e2311da2339f5872

**Describe the bug**
When enough bindings are present, you can't scroll down to select which DBCs you want to import/export.

**To Reproduce**
1. Add a lot of bindings to the folder
2. Click Import/Export
3. Bingo

**Expected behavior**
Add a bar on the right, so you can scroll in the menu

**Screenshots**
https://imgur.com/a/bJXBCWM

**Comment by stoneharry** [comment]
Not the cleanest solution in the world, but I added a scroll bar in 686e9b83f581c5ff31446e8acf91982b761a0de8. I will leave this open until a new release is published.

**Comment by stoneharry** [comment]
Released version v1.9.5 - closing.
