### ISSUE TITLE
Cannot Save Spell Targets on 1.12.1

### ISSUE THREAD

**Issue by rosen40** [stoneharry/WoW-Spell-Editor#109]
**Spell editor version**
09b2a76

**Describe the bug**
Failure to save Spell Effects Targets data after its been changed on 1.12.1 WoW version/dbc.

**To Reproduce**
1. under  Effects > Effects 2 
2. Change Target A or B to a new value
3. Save Spell Changes
4. Select another spell
5. Select again the spell you edited and see that the edited target is 0 and further edit attempts will result in the same.

**Expected behavior**
Expecting Spell Targets to save to desired value, obv.

**Comment by stoneharry** [comment]
need to look a bit more into this.

It looks like in 1.12 I am using the Target value to set the Class Masks at the moment. When you save it is setting the Targets to the Class Masks. 

This is obviously wrong, but raises the question what should the class mask values be loaded from and saved to.

I'll spend a bit more time on this at the weekend.

**Comment by stoneharry** [comment]
Fixed in  ea0fbdd, but I will leave this issue open until a new release is published.

It looks like class masks are not available at all in 1.12. I also found a bug which I've fixed in this where the EffectRealPointsPerLevel were being saved as a int instead of a float value.

**Comment by stoneharry** [comment]
Released version v1.9.5 - closing.
