### ISSUE TITLE
Bug when creating a new spell copying an id

### ISSUE THREAD

**Issue by azraeldestiny01** [stoneharry/WoW-Spell-Editor#110]
**Spell editor version**
Please provide the spell editor version you are using.
**Release Build v1.9.4**

**Describe the bug**
**Do not copy the existing ID by following the first steps when pressing the "new spell" button**

**To Reproduce**

1º I install the application
2º I configure DBC directory and binding directory in their corresponding folders (indicated in the image below)
3º I save the changes
4º I give a new spell
5º It tells me that if I want to copy an existing spell
6º I introduce this spell "35025" (blood elf mount)
7º He asks me for a new ID to copy the content to
8º I introduce this ID 1000002 (to have it with the same ID as the new frame)
9º The following error appears (screemshoot)

**Expected behavior**
**Copy an existing spelling to work on a new one (First Procedures)**

**Screenshots**
https://media.discordapp.net/attachments/415944535718494208/718144460059312178/12.png?width=770&height=449

**Additional context**

**-I use the ESES version of WoW (although I think it is not important, I am a Spanish-Spain user)
-Copy the file spell.dbc from the server to the corresponding folder of DBC335_woltk to have the same dbc as the server (otherwise it would break many spells that are already integrated)
-Although I did the above commented. Also test with the spell.dbc itself that was included in the installation giving the same error.

Thank the creator for the great work with this program, I have seen tutorials on its use and I would love to be able to use it to create my first custom mount :)**

**Comment by stoneharry** [comment]
Hello, I believe you might be using mixed locales?

See #55, when using another locale you need to update all the DBC files, not just the spell.dbc.

If you are still getting the error after doing this, please can you upload your DBC files for me to debug with?

**Comment by Bunnyblock2** [comment]
Hi, I appear to be getting the same exact error, but with the English locale. I used the default DBC packaged with the Spell Editor, but I also tried my own DBC. When I try to copy any ability I get the following error:

```
 System.IndexOutOfRangeException: There is no row at position 0.
   at System.Data.RBTree`1.GetNodeByIndex(Int32 userIndex)
   at System.Data.DataRowCollection.get_Item(Int32 index)
   at SpellEditor.MainWindow.<Button_Click>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
I've tried the x86 and x64 executables, and i've tried SQLite and MySQL. I also tried version 1.9.5, 1.9.4, and 1.9.3 of the Spell Editor.

**Comment by stoneharry** [comment]
Haha, glad you got it working. :)

There used to be a prompt when you first open the program that asked if you want to import data. I should maybe add that back in, this seems to catch quite a few people out.

I'm going to close this issue if you're happy.
