### ISSUE TITLE
Wrong spell school display on 1.12 version

### ISSUE THREAD

**Issue by rosen40** [stoneharry/WoW-Spell-Editor#111]
**Spell editor version**
     09b2a76

**Describe the bug**
It seems that in 1.12 DBC, spell school flags have a different setup than 3.3.5 regarding which value corresponds to what school so the editor displays wrong string? 
From my obeservations its as follows:
Arcane spells  - shown as Holy and Fire school
Fire spells - shown as Holy school
Nature spells - shown as Physical and Holy school
Holy spells - shown as Physical school
Frost spells - shown as Fire school
Shadow Spells - Shown as Physical and Fire

**To Reproduce**
1. Go to the Base page of a spell which you are sure what the school should be with a default DBC
2. See wrong spell school 

**Expected behavior**
Editor should display correct name of spell school.

**Comment by stoneharry** [comment]
Fixed in 57ddd9b4f1c0565315efbaa092a0306c8919f85f, but I will leave this open until a new release is published.

**Comment by stoneharry** [comment]
Released version v1.9.5 - closing.
