### ISSUE TITLE
Spell Visual Map

### ISSUE THREAD

**Issue by yun000** [stoneharry/WoW-Spell-Editor#112]
How do I use this tool? SpellVisualMapBuilder.exe
I can't import CreatureTemplate.sql
The database is wrong

**Comment by stoneharry** [comment]
The emulator database structures regularly change, and vary with each emulator. I made this tool once specifically for the emulator and version I was using.

The structure will need to be updated manually to match the emulator and version you are using. There is an enhancement request to make a SQL template that can be changed, which is tracked here: #101 

Unfortunately I have been preoccupied with other projects recently and haven't got round to finishing this enhancement request.
