### ISSUE TITLE
Export Function is broken

### ISSUE THREAD

**Issue by MoonSoo9079** [stoneharry/WoW-Spell-Editor#116]
**Spell editor version**
v1.9.6

**Describe the bug**
The export function exports an invalid spell.dbc file.

**To Reproduce**
1. Open the Spell Editor
2. Import the required dbc files
3. Export the dbc files
4. Open the exported Spell.dbc file in a dbc editor
5. See invalid entries

**Expected behavior**
The exported content of the Spell.dbc is expected to look like this:
![grafik](https://user-images.githubusercontent.com/55256762/87246964-16139a80-c451-11ea-997d-48a8e5043022.png)

**Screenshots**
Instead it looks like this:
![grafik](https://user-images.githubusercontent.com/55256762/87246979-32173c00-c451-11ea-9576-dd6cc6dcbe47.png)

**Additional context**
The export function works as expected in v1.9.5. The imported dbc files are the ones provided in the DBC_335_wotlk folder.

**Comment by stoneharry** [comment]
Thanks for reporting this, I was not aware something so fundamental was broken. I tested it exported the DBC but did not test it in game.

**Comment by stoneharry** [comment]
Fixed in #72934880ee55fb277da9513cf22a11dab32e7e19. Leaving this issue open until a new build is published (shortly).

**Comment by stoneharry** [comment]
Fixed in v1.9.7, closing and thanks for reporting this.
