### ISSUE TITLE
About finding the correct Visual Spell Id /Map

### ISSUE THREAD

**Issue by chamorrorenzo** [stoneharry/WoW-Spell-Editor#118]
hello, this is exactly what i was looking for (big thanks), finding cool visual effects for my project

so I managed to make the SpellVisualMap to work, and now I see all the visuals spawned and everything working nice

now my question is, how do I know what the visual IDS are for this visual effect, lets say I ding some fire effect on the map, but how do I find the ID to use ?

when all I know is their path name?

maybe im missing something?
thanks

**Comment by stoneharry** [comment]
So this isn't as straight forward as you might expect. A spell visual is made up of visual kits, visual effects, and/or visual attachments.

![data structure image](https://i.imgur.com/T2kyjhi.png)

I generally find an existing visual effect or visual attachment that is using the model that you want to use. It's then a case of copy + pasting this to your spell, or just using the same spell visual id.

If you want to create a new spell visual, set the visual Id to 0 then copy and paste another spells visual kit into your spell visual kit. It will create a new spell visual and copy over the data linking everything up.

```sql
SELECT * FROM spellvisualeffectname WHERE FilePath LIKE "%Fireball%.mdx";
```

The spell editor UI could definitely be enhanced to allow you to query for things like this, but I don't have the time right now.

**Comment by chamorrorenzo** [comment]
thanks for the quick response!

**Comment by stoneharry** [comment]
I'm going to close this assuming it answers your question(s) satisfactorily. Please feel free to reopen or create a new issue if you have further questions.
