### ISSUE TITLE
Creating tables for database does not match case

### ISSUE THREAD

**Issue by ph1lt0r** [stoneharry/WoW-Spell-Editor#119]
**Spell editor version**
3.3.5A 12340

**Describe the bug**
Creating a database the spells table is created as Spells, but the client on windows 10 looks for (dbname).test

**To Reproduce**
1. create the database and tables from a windows 10 client on a mysql database on a remote linux server

**Expected behavior**
The attached screenshot should not happen.

![Capture](https://user-images.githubusercontent.com/47256510/89722641-b0fc8780-d9b1-11ea-998c-84cb9b352006.JPG)

**Comment by stoneharry** [comment]
I guess you can workaround by using a database called test?

I'm not sure what could be causing this without some research. It could be your user does not have permissions to create/use the database.

**Comment by Sanavesa** [comment]
Unfortunately I saw this after I made my bug issue on the same topic [here](https://github.com/stoneharry/WoW-Spell-Editor/issues/120). Nevertheless, I added more detail and a way to fix this issue. A temporary solution would be to go in your SQL DB and rename Spell to spell, and it would work correctly.

**Comment by stoneharry** [comment]
Should finally be fixed in v2.0.3.
