### ISSUE TITLE
MySQL Table name creation mismatches table name in code

### ISSUE THREAD

**Issue by Sanavesa** [stoneharry/WoW-Spell-Editor#120]
**Spell editor version**
Release Build v1.9.7 for WoW 3.3.5a 12340

**Describe the bug**
The editor shows _"myDatabase.spell"_ table doesn't exist after selecting the MySQL option. The table created in the database is **Spell** rather than **spell**.

**To Reproduce**
1. Run fresh copy of WoW Spell Editor v1.9.7.
2. Select MySQL.
3. Fill MySQL details correctly.
4. You'll see the error as shown in the screenshot below: "Table 'spell_editor.spell' doesn't exist"

**Expected behavior**
Table names are case-sensitive, thus the tables created mismatch the name of the tables used in code. _Spell_ should be _spell_, unless the code was updated to recognize _Spell_ rather than _spell_.

**Screenshots**
![Error in Spell Editor](https://user-images.githubusercontent.com/31108136/92145229-92f33d00-ee20-11ea-9b15-92c4efbc2d76.png)
![Table created in Database](https://user-images.githubusercontent.com/31108136/92145250-9d153b80-ee20-11ea-8b5d-c24be8f320db.png)

**Additional context**
Internally, the application creates the table names based off the Bindings_335_wotlk folder. Since the binding for the Spell.dbc is Spell.txt, the table created will be called Spell. The code for the table creation can be found at MySQL.cs, in the GetTableCreateString function.

Possible solution: Replace all occurrences of spell to Spell in the code. One example is:
_SpellGUIV2\MainWindow.xaml.cs_ line 1131:
`var row = adapter.Query($"SELECT * FROM `spell` WHERE `ID` = '{oldIDIndex}' LIMIT 1").Rows[0];`
becomes
`var row = adapter.Query($"SELECT * FROM `Spell` WHERE `ID` = '{oldIDIndex}' LIMIT 1").Rows[0];`

**Comment by stoneharry** [comment]
Should finally be fixed in https://github.com/stoneharry/WoW-Spell-Editor/releases/tag/v2.0.3
