### ISSUE TITLE
Fields size does not match the DBC header record size?

### ISSUE THREAD

**Issue by dogabeey** [stoneharry/WoW-Spell-Editor#123]
Hey. I'm having hard time to get the program work, as I constantly get the following exception:

> System.Exception: Binding [...\WoW Spell Editor 1.9.7\DBC_335_wotlk\AreaTable.dbc] fields size does not match the DBC header record size; expected record size [72] got [144].
>    at SpellEditor.Sources.DBC.DBCReader.ReadDBCRecords(DBCBody body, String bindingName)
>    at SpellEditor.Sources.DBC.AbstractDBC.ReloadContents()
>    at SpellEditor.Sources.DBC.AreaTable..ctor()

I'm using 3.3.5a, and checked many times to make sure I use the correct folders. Can you help please?

Thanks.

**Comment by stoneharry** [comment]
The expected DBC record size based on the binding files configured is 72, but the actual DBC record size is 144.

Check your config has the right DBC and binding folder paths set. Also check the right version is selected. Restart the program after making config changes. 

Let me know if it still doesn't work.

**Comment by dogabeey** [comment]
Thanks for response. I use default folders inside the repo for bindings and dbc (bindings335_wotlk and DBC335_wotlk respectively). But I also tried DBC file that I extracted from wotlk client itself (wow build config is also correct).

**Comment by stoneharry** [comment]
Are you using mysql or sqlite? If mysql then make sure you are using a unique database

**Comment by dogabeey** [comment]
Mysql. Not sure what you meant by unique though. I used latest TrinityCore query for creating database here  https://github.com/TrinityCore/TrinityCore/releases

**Comment by stoneharry** [comment]
You need to use a different database to Trinity Core. The spell editor is not compatible with trinity core in any way, you need to use a different database.

**Comment by dogabeey** [comment]
Oh I see. Thanks.

**Comment by stoneharry** [comment]
If this fixes your issue we can close this. Please let me know how it goes. Thanks :)

**Comment by dogabeey** [comment]
It did, I guess. Though I don't have any other core other than trinity right now so I can't try ^^

Kind of off-topic but; which framework do you suggest instead of trinity? From what I see people generally consider it as most up-to-date and bug-free core out there but I'm open to other options.

**Comment by stoneharry** [comment]
I use trinity for my personal project.

**Comment by stoneharry** [comment]
There might be some confusion here, the process is to import your spell.dbc into the spell editor DB. When you are finished making edits export it back to a new spell.dbc and deploy that to your emulator and client.

**Comment by stoneharry** [comment]
Closing this issue - feel free to reopen or create a new issue if you think there is still a problem or have further questions.
