### ISSUE TITLE
Shadowmeld is not loaded by the editor

### ISSUE THREAD

**Issue by arkynata** [stoneharry/WoW-Spell-Editor#125]
version 1.9.7

Shadowmeld is missing in the list of spells. It should be entry 20580, which is present in the dbc, but it isn't loaded by the editor. Three other versions show up if you filter by spell name:

58984
62196
62199

I think these are later versions from wotlk? They are not present in the dbc as far as I can tell, so I don't know why they appear.

1. Configure the editor to WoW version 1.21.1, set the bindings and dbc directories to the vanilla folders.
2. Restart the editor and in the field "Go to spell id:" type "20579", check the list to the left; the next entry is missing.
3. In the field "Filter by name:" type "shadowmeld", you will see the three incorrect(?) versions.

If there is something I might have misunderstood then I apologize for the false report, I am still new to both the editor and the WoW database structure.

**Comment by stoneharry** [comment]
How are you checking if it is present in the DBC? Are you using the DBC files distributed with the releases of this program?

I have only done a quick test using wotlk, but this spell id 20580 does not exist client side or server side.

**Comment by arkynata** [comment]
I am using a DBC Editor, I believe it is this one:
http://www.ac-web.org/forums/showthread.php?74919-DBC

But I am not entirely sure, I could check if you want to use the same program.
I simply opened the file and checked the entries.

**Comment by arkynata** [comment]
It seems to be using the wrong descriptions as well?
![wotf](https://user-images.githubusercontent.com/73134686/96512493-dbe04300-1260-11eb-9901-9d8537735dc1.png)

The other spells showing up do not exist in the DBC either I think...
![dbc](https://user-images.githubusercontent.com/73134686/96512760-43968e00-1261-11eb-8cab-b0257cc8c249.png)

When ordering by id, there aren't any higher than 32061

Perhaps the configuration is bugged? It seems like the program is still pulling data from the wotlk files...?

**Comment by stoneharry** [comment]
So using 1.12.1 I am able to see the spell:

![screenshot](https://i.imgur.com/klwvGIR.png)
![config](https://i.imgur.com/TXy6cE2.png)

Can you try dropping your entire spell database, then starting the program and doing an import?

The highest spell ID in my import is 32061:

![screenshot](https://i.imgur.com/mDhSjnO.png)

I suspect you have 3.3.5 data imported. I can see this in a 3.3.5 dbc:

![screenshot](https://i.imgur.com/rTNJdBs.png)

**Comment by arkynata** [comment]
I see you are using MySQL rather than SQLite, should that make a difference?

**Comment by stoneharry** [comment]
> I see you are using MySQL rather than SQLite, should that make a difference?
> 
> EDIT: I made a clean reinstall and it works with SQLite. Sorry about the bother, seems like the problem was on my end!

Good to see it is working for you. :) There's definitely some improvements to be made around changing config and when the table structures are created.

Because this issue is resolved for you, I'm going to close this out.
