### ISSUE TITLE
.exe not opening for first launch

### ISSUE THREAD

**Issue by VikingSheep** [stoneharry/WoW-Spell-Editor#131]
**Spell editor version**
1.9.7

**Describe the bug**
Neither .exe file (x64 or x86) open the program despite this being a fresh install. Debug_output.txt says the following and nothing else upon attempting to run:
[17:56:01.7250|INFO|SpellEditor.MainWindow] ######################################################
[17:56:01.7570|INFO|SpellEditor.MainWindow] Starting WoW Spell Editor - 3/25/2021 5:56:01 PM
[17:56:01.7570|INFO|SpellEditor.MainWindow] ######################################################

**To Reproduce**
1. Install fresh copy of SpellEditor
2. Navigate to destination folder and attempt to run either executable
3. Check debug_output.txt
4. Result: nothing happens

**Expected behavior**
I expected the program to ask me where to find my server database and to choose an SQL type, but no new windows opened nor any indication that the program was actually running. 

**Screenshots**
No screenshots will help here, but the text provided above shows the output from running the .exe

**Additional context**
Running windows 10, tried restarting my computer already, have not tried earlier versions of the program yet.

**Comment by stoneharry** [comment]
Is there an error.txt? Could your anti-virus be blocking it?

**Comment by VikingSheep** [comment]
SOLVED

The anti-virus was in fact blocking it from installing correctly (bindings folders simply weren't there, and many DBC files were missing). Tried it with older versions and similar issues kept happening, so I guess AVG just doesn't like your program. Regardless, I temporarily disabled it completely and installed v1.9.7 and now it has all the files.

**Comment by stoneharry** [comment]
Awesome, thanks for the update.

Unfortunately there's not a lot I can do about anti-virus not liking it. Most anti-virus work via a whitelist method these days. A relatively unknown executable (only a few thousand downloads) is not going to be liked.

Closing this issue.
