### ISSUE TITLE
Bad icons loading

### ISSUE THREAD

**Issue by browller** [stoneharry/WoW-Spell-Editor#134]
**Spell editor version**
v 1.9.8

**Describe the bug**
I'm using custom icons + huge Spellicon.dbc list, with that the spell editor takes longer than normal to load icons, sometimes making the spelleditor to crash too.

**To Reproduce**
Just use my SpellIcons.dbc and Icons folder

Icons/DBC:
https://www.mediafire.com/file/x9gjiyqaybxy957/Interface.rar/file

**Comment by stoneharry** [comment]
@browller has tested e210e07597b7f43c16595b8b58cc1061b07d939f locally and it works much better for his use case. However I think this approach does not work as well when you don't have quite so many icons.

I think this should be changed into a config option before being merged to master.

**Comment by stoneharry** [comment]
This has been merged in 8eccbf0d5d63beb409c91aded6055804422dfeb4 and is configurable. I will leave this issue open until a new release is published.

**Comment by stoneharry** [comment]
Closing this because it is included in Release Build v1.9.9.
