### ISSUE TITLE
[FEAT] MySQL Ping to keep connection alive.

### ISSUE THREAD

**Issue by tikki100** [stoneharry/WoW-Spell-Editor#136]
**Is your feature request related to a problem? Please describe.**
Yes - after a short period of not using the editor, SQL connections to the database gets timed out. This results in errors and requires a restart of the application.

**Describe the solution you'd like**
Make the thread responsible for the SQL connection ping the SQL database every 5 minutes to keep the connection alive.

**Comment by stoneharry** [comment]
Implemented in 7f42044, I will keep this issue open until a new release has been published.

**Comment by stoneharry** [comment]
Closing this because it is included in Release Build v1.9.9.
