### ISSUE TITLE
Option to export 1 or multiple of spells as standalone SQL code.

### ISSUE THREAD

**Issue by avarishd** [stoneharry/WoW-Spell-Editor#141]
There should be an option to export 1 or multiple spell(s) as standalone SQL code.

I.E

You modify Charge (100) and you want to export only this spell as SQL code. You select it and hit export and in the Export folder (or just in the program itself) you have the raw SQL code.

**Comment by stoneharry** [comment]
You can do this with any MySQL GUI, I use SQLyog Community Edition myself. What advantage would there be in me adding this to the spell editor program? It saves having an additional program open but it's a lot of effort for something that already exists, and you need to have a SQL editor open anyway for all the other database work you do when working with emulation.

**Comment by avarishd** [comment]
> You can do this with any MySQL GUI, I use SQLyog Community Edition myself. What advantage would there be in me adding this to the spell editor program? It saves having an additional program open but it's a lot of effort for something that already exists, and you need to have a SQL editor open anyway for all the other database work you do when working with emulation.

I think that suggestion came as an idea after https://github.com/stoneharry/WoW-Spell-Editor/issues/140 . But yes I agree with you.
