### ISSUE TITLE
Case sensitivity with linux SSH Exporting Issue

### ISSUE THREAD

**Issue by VladShinobi** [stoneharry/WoW-Spell-Editor#144]
**Spell editor version**
12340

**Describe the bug**
The issue happens when I attempt to export the DBCs. None of the options are available to be ticked, and my database is creating another db table in the `DBC_Files`  with an uppercase first letter. I am running my SSH through linux

**To Reproduce**
1. Use Linux SSH
2. Attempt to export
3. Not be able to export

**Additional context**
Sorry, this is my first ever github bug report

**Comment by Ember-RP** [comment]
I'm having the same issue as well with case sensitivity. Cannot export my spell table on the latest release.

**Comment by stoneharry** [comment]
This should be fixed in v2.0.3. Please feel free to reopen / comment on this if the solution does not work. Closing.
