### ISSUE TITLE
Sort Durations by duration rather than ID

### ISSUE THREAD

**Issue by T1ti** [stoneharry/WoW-Spell-Editor#146]
**Is your feature request related to a problem? Please describe.**
Finding the duration you're looking for can be very exhausting it requires scrollnig through hundreds until you find the one you want 
![image](https://user-images.githubusercontent.com/40864460/137422981-2d090b17-20b1-4a26-9c97-c1c89a63b1de.png)

**Describe the solution you'd like**
Just sort duration by duration instead of ID. like 1sec>2sec>5sec>1min>5min..

**Any other comments/information**

**Comment by stoneharry** [comment]
Fixed in 4a8696aeec577749475342ca3f150ed405504e04. I will leave this issue open until a new release is published and potentially for sorting a few other fields.

**Comment by T1ti** [comment]
could be useful for spell effect radius too

**Comment by stoneharry** [comment]
Release Build 2.0 has been pushed, closing this.
