### ISSUE TITLE
Another Question

### ISSUE THREAD

**Issue by Sulan2** [stoneharry/WoW-Spell-Editor#158]
Hey again harry and thanks for the answer on my last question, sry I didnt reply anything had a lot of other things going on

Anyway I got a new question that I would love to have your help on

The ability disengage 781 for some reason cannot be used OUTSIDE of combat. What is it that achieves this?
It feels like there should be a box to tick in Attributes or Attributes2 for this because there is a box for spells/abilities being stopped from being used IN combat. 
But there isnt any box to tick for stopping spells/abilities from being used Outside of combat

I want to make it so disengage is useable both in and outside of combat

**Comment by stoneharry** [comment]
It's a spell script as given by the `spell_script_names` world database table under TrinityCore.

`spell_hun_disengage`

Checking `spell_hunter.cpp`:

```c++
// 781 - Disengage
class spell_hun_disengage : public SpellScriptLoader
{
    public:
        spell_hun_disengage() : SpellScriptLoader("spell_hun_disengage") { }

        class spell_hun_disengage_SpellScript : public SpellScript
        {
            PrepareSpellScript(spell_hun_disengage_SpellScript);

            SpellCastResult CheckCast()
            {
                Unit* caster = GetCaster();
                if (caster->GetTypeId() == TYPEID_PLAYER && !caster->IsInCombat())
                    return SPELL_FAILED_CANT_DO_THAT_RIGHT_NOW;

                return SPELL_CAST_OK;
            }

            void Register() override
            {
                OnCheckCast += SpellCheckCastFn(spell_hun_disengage_SpellScript::CheckCast);
            }
        };

        SpellScript* GetSpellScript() const override
        {
            return new spell_hun_disengage_SpellScript();
        }
};
```

**Comment by Sulan2** [comment]
Thank you!, I removed it from world database and it works perfectly now
