### ISSUE TITLE
Is there any where to contact u for further question?

### ISSUE THREAD

**Issue by Sulan2** [stoneharry/WoW-Spell-Editor#159]
Hey harry would it be possible to get a text chat with u somewhere like on discord for further spell changing problems?
would love to learn what you know

**Comment by stoneharry** [comment]
I prefer to answer questions in an open forum for the most part because then it is somewhat documented for anyone else having the same question or issue.

You can find me in the WoW modding Discord: https://discord.gg/WamE5UU
