### ISSUE TITLE
Stances are incorrectly handled

### ISSUE THREAD

**Issue by NixAJ** [stoneharry/WoW-Spell-Editor#160]
**Spell editor version**
2.0.0

**Describe the bug**
The stances provided under Flags -> Misc does not appear to correspond to the correct values

**To Reproduce**
1. Go to spell 703
2. Click on Flags -> Misc

**Expected behavior**
This spell requires the stance "Stealth", however Spirit of Redemption is selected instead, changing it to stealth makes it require Shadowform if you check ingame.

**Comment by T1ti** [comment]
Currently stances are hardcoded and wrong 
![image](https://user-images.githubusercontent.com/40864460/149722156-a4de0402-bc7d-4f80-8ff3-338dc60f204f.png)

![image](https://user-images.githubusercontent.com/40864460/149722169-ee6ebf28-ad55-430d-8e44-84388ea3a862.png)
those two empty entries are missing
