### ISSUE TITLE
Think there is a bug with Flags Misc Stances section

### ISSUE THREAD

**Issue by Sulan2** [stoneharry/WoW-Spell-Editor#165]
I tried to create a new spell that is based on another spell
This new spell I wanted to only be useable in moonkin form so I crossed the moonkin box in Flags Misc section and noticed that it did not correlate to the right thing in the game.
Doing some more research I noticed that there was a few others boxes that were also wrong

I first tried this in version 2.0.0 and updated to 2.0.1 and its wrong in both versions

Here is what I found to be wrong

Box in the editor   / What it acctualy is in the game
Moonkin                  = flight normal
Flight normal          = epic flight
Flight Epic               = Undead
Undead                   = ????? (I dont know what this does but it isnt Moonkin form at least)
Spirit of Redemption = Stealth (This can be confirmed by looking at cheap shot 1833)
Stealth                     = Shadow form
Shadow                   = Frenzy?? I dont know what this is but it says Frenzy in game

With all of this said, I wanted to find Moonkin Form but I could not find that any of the boxes was moonkin Form

**Comment by stoneharry** [comment]
Already known under #160 , I've just not got around to fixing it yet. It's a very quick fix.

**Comment by stoneharry** [comment]
Fixed in v2.0.4 - closing.
