### ISSUE TITLE
How to target all "green" NPCs with "TRIGGER_SPELL" to apply Renew-like regen.

### ISSUE THREAD

**Issue by TheQwertyOne** [stoneharry/WoW-Spell-Editor#168]
I'm trying to construct a Holy Nova like spell which will damage enemies and heal all greens, be they party members, random passer-bys or _quest NPCs_. Is there any way to target "green" NPCs in Spell Effects? 

I am trying these options (with my custom HoT spell 700991), they don't work except on the char itself:
![28 02 22_16-22-39_aruMyoMqsZ](https://user-images.githubusercontent.com/100481618/155990576-80f24bf7-65e8-4203-9ddc-a565b1473739.png)

**Comment by stoneharry** [comment]
You can target ALLY, ENEMY, or ENTRY generally. Entry is both players and creatures (all units).

What you probably want is a spell script that validates the target, then in the spell definition you allow it to select anything.

See `spell_generic.cpp` for example spell scripts. These are linked to spells in the `spell_script_names` world database table.

**Comment by TheQwertyOne** [comment]
> You can target ALLY, ENEMY, or ENTRY generally. Entry is both players and creatures (all units).
> 
> What you probably want is a spell script that validates the target, then in the spell definition you allow it to select anything.
> 
> See `spell_generic.cpp` for example spell scripts. These are linked to spells in the `spell_script_names` world database table.

Thanks for the answer. Scripting is a bit beyond me. But... 

If I set up Spell Effect 2 to APPLY_AURA on any ENEMY, that aura being SPELL_AURA_MOD_HEALING_DONE_PERCENT at -100%, but then set up Spell Effect 3 to TRIGGER_SPELL on any ENTRY, that spell being my healing spell, which uses SPELL_AURA_PERIODIC_HEAL, it should do the trick...

I would've liked to find an appropriate EFFECT_IMMUNITY Misc Value but the one I can find prevents only Direct Healing, leaving Healing over Time intact (Veil of Darkness from old Deathknight NPCs)
