### ISSUE TITLE
Spell not showing up in running client

### ISSUE THREAD

**Issue by Illynova** [stoneharry/WoW-Spell-Editor#169]
Hey there, amazing GUI love it love it love it.
First time trying to mod anything, i feel like im doing stuff right but the result isnt showing.
I have been trying to edit a spell through WoW Spell Editor 1.12.1, copied an existing one and its chained spell and named them 40001, 40002
-I exported the files as .dbc
-moved those files to my mangos data\dbc folder
-created an .mpq  (tried thru the spell editor and thru mpq editor) and moved that to data folder of client

so i started up the mangos server, logged into the gm account, and did a .learn 40001 and it wrote syntax error like it does not have that spell in its database or something....idk wtf im doing wrong.
als did a .lookup spell seal of light, and all the original versions of the spell are listed, and 40001,40002 are not listed there.

can someone help meh plzz ❤️ ?
![unknown](https://user-images.githubusercontent.com/101522697/158073946-966f2cf4-6532-4296-ab03-98f32af5ae73.png)

**Comment by T1ti** [comment]
vmangos requires adding the spells to its database as well

See https://github.com/stoneharry/WoW-Spell-Editor/issues/91#issuecomment-635557187

You have to copy the data from your spell_editor table to the vmangos spell table, which can be done using this querry.
