### ISSUE TITLE
Redesign "Saved Spell (ID)" Popup

### ISSUE THREAD

**Issue by VladShinobi** [stoneharry/WoW-Spell-Editor#172]
Hello,

**Intro:** I would like to propose a feature change/redesign for how the "Saved" popup. 

**The Issue:** As it stands, it currently gets in the way of the last spell, which makes it quite annoying to see the ID, name, or even to select it. As we both know how painful it is to make a lot of spells, this just adds another step to an already tedious process. 
**[Example of what I am describing](https://i.gyazo.com/b6084d5844882cc4038fd329c1dc5b85.png)**

**Proposition:** I would like to ask that this perhaps is migrated to the top right corner in a small form (Perhaps just a green box with a emoji/check mark to indicate it is indeed saved. The "green" will stand out easily, and at a glance be able to tell if it was saved rather than having a gray on gray (same color) popup. This will also remedy getting in the way/overlapping on the last spell in the list. 

Thank you Harry

**Comment by stoneharry** [comment]
I'm not actively working on the spell editor at the moment, but I can add this when I do eventually have time to work on it again.

**Comment by stoneharry** [comment]
With the next release the popup message will now auto close as soon as you click or after 1.8 seconds: cd64a479680929ea2ffebf8183946fa230f3f70c

**Comment by stoneharry** [comment]
Closing with v2.2.2.
