### ISSUE TITLE
Error: Failed to load core DBC files based on the bindings, have you got the right WoW version, bingdings folder, and DBC folder configured?

### ISSUE THREAD

**Issue by felixjiang** [stoneharry/WoW-Spell-Editor#176]
I keep getting this error.  The MySQL connection info I enterd should be correct because this is exactly the params I used in MySQL WorkBench to log in MySQL. Then what caused this issue?

![image](https://user-images.githubusercontent.com/3860638/168481756-af16f557-96cc-4f34-9140-d0d6755a6e55.png)

![image](https://user-images.githubusercontent.com/3860638/168481892-2a03e57e-00c0-4efa-a897-e28416f7a46e.png)

**Comment by felixjiang** [comment]
Seems the first error is gone. Then I got another error:

![image](https://user-images.githubusercontent.com/3860638/168483249-c18e6d79-249a-43b8-9c14-788087e9686c.png)

**Comment by felixjiang** [comment]
I created a separate DB SpellEditor, but the problem still exists.

![image](https://user-images.githubusercontent.com/3860638/168717389-2b0a5c31-c4bb-45d4-b9bd-cd81bbd21632.png)

![image](https://user-images.githubusercontent.com/3860638/168717441-f8a0907a-4680-4443-a352-c4f3e96ae389.png)

**Comment by stoneharry** [comment]
Can you upload your `debug_output.txt`?

**Comment by felixjiang** [comment]
Here it is.

[debug_output.txt](https://github.com/stoneharry/WoW-Spell-Editor/files/8713132/debug_output.txt)

**Comment by felixjiang** [comment]
waiting for the solution :)

**Comment by stoneharry** [comment]
It looks to me like your database structure is incorrect, but it is hard to tell from my phone.

**Comment by felixjiang** [comment]
These are what inside the MySQL instance, default installation plus the databases from AzerothCore. 

![image](https://user-images.githubusercontent.com/3860638/169552605-129a5e37-f724-480f-9502-44dc03b0258d.png)

**Comment by stoneharry** [comment]
I don't see a Spell Editor database?

**Comment by felixjiang** [comment]
You mentioned earlier that "You need to set the spell editor to use a database that does not already exist. For example: spelleditor."

I think you mean the database I specify in SpellEditor shouldn't exist in MySQL and SpellEditor will create it for me.

**Comment by felixjiang** [comment]
I created a blank database spelleditor in MySQL and run SpellEditor again. Now magic happens. SpellEditor starts with a "new warning" saying something like key not found. Then it continues with the below screenshot. But it has been like this for an hour, and nothing happens in the spelleditor database so far.
![image](https://user-images.githubusercontent.com/3860638/169632638-1bfddb4a-7e86-49f7-91eb-7288deff1ee2.png)

**Comment by stoneharry** [comment]
I'm going to need your `debug_output.txt` and any `errors.txt`

**Comment by felixjiang** [comment]
I want to first make sure that the steps to setup the tool is correct.

1. Download the tool to any local folder.
2. Create a blank database, named spelleditor in my case, in MySQL.
3. Run Spell Editor.

It is expected to work, right?

My OS: Windows 10 (Simplified Chinese) with all the latest patches.

**Comment by stoneharry** [comment]
For step 2, you don't even need to create a blank database, just configure one that does not already exst.

After step 3 you need to import the DBC files to SQL.

**Comment by felixjiang** [comment]
The started from scratch. Here is the error I got (a different one) and the debug_output.txt

![image](https://user-images.githubusercontent.com/3860638/169731318-c1d5209d-7135-4da5-a619-9de5b1de360e.png)

[debug_output.txt](https://github.com/stoneharry/WoW-Spell-Editor/files/8750850/debug_output.txt)

**Comment by felixjiang** [comment]
I also recorded my setup process in a video (100 MB). I shared it through from my OneDrive: https://1drv.ms/v/s!AijnrbxgTM_PgsYVR4DiVf8HHPTRwA?e=IPpwOb

**Comment by stoneharry** [comment]
5576cba9f8e5171fd0851ab5b6702b2952410c20 may help with this, I can make a new release.

**Comment by stoneharry** [comment]
Can you test with https://github.com/stoneharry/WoW-Spell-Editor/releases/tag/v2.0.2 please?

**Comment by felixjiang** [comment]
2.0.2 has the same issue on my side. I will look into your other suggestions tomorrow. Thanks for your consistent help.

**Comment by felixjiang** [comment]
Also I uploaded my spell.dbc file.

[Spell.zip](https://github.com/stoneharry/WoW-Spell-Editor/files/8783613/Spell.zip)

**Comment by stoneharry** [comment]
252ffaf7ed7690fbe52d7c4443aaa44d5dd01b12 may fix this, I think all three issues are suffering from the same problem. I will post a new release soon.

**Comment by stoneharry** [comment]
Confirmed bumping MySQL.Data library version from 8.0.27 to 8.0.29 fixed this error for #178.

**Comment by stoneharry** [comment]
This should be fixed in v2.0.3. Please feel free to reopen / comment on this if the solution does not work. Closing.

**Comment by felixjiang** [comment]
@stoneharry You made my day. Everything works this time with 2.0.3, like magic. Thanks so much for your great help. Also thumb up for your great passion in this tool as well.
