### ISSUE TITLE
MySQL import failing (wrong table name -missing capitals- ?)

### ISSUE THREAD

**Issue by ayahuasca-ruderalis** [stoneharry/WoW-Spell-Editor#178]
**Spell editor version**
Latest release 2.0.2
**Describe the bug**
Kind of duplicate of #176 
I'm using mariaDB on the server
After reading #176 I tried replacing all the DBCs in the SpellEditor folder by the ones in my server data folder (frFR DBCs) and now the problem is not the same at all. From my understanding it seems to import in database.spell table while the table name is 'Spell' and not 'spell' ?

**Screenshots**

![Capture_1](https://user-images.githubusercontent.com/95539849/170574939-9db030ed-b87b-40c3-9ea7-9ca0bcb14c12.PNG)

**Comment by ayahuasca-ruderalis** [comment]
Here are the DBCs I use.

[DBC_335_wotlk.zip](https://github.com/stoneharry/WoW-Spell-Editor/files/8781971/DBC_335_wotlk.zip)

**Comment by stoneharry** [comment]
![screenshot](https://i.imgur.com/roWSxzn.png)

I think this might be related to #144 . I will look into refactoring all the queries to use consistent capitalisation and release that as another minor update.

**Comment by stoneharry** [comment]
Confirmed bumping MySQL.Data library version from 8.0.27 to 8.0.29 fixed this error.

**Comment by stoneharry** [comment]
This should be fixed in v2.0.3. Please feel free to reopen / comment on this if the solution does not work. Closing.
