### ISSUE TITLE
Suggestion: Option to change default Export patch name

### ISSUE THREAD

**Issue by JyriaLycion** [stoneharry/WoW-Spell-Editor#180]
I'd personally like to see a setting to change the default Patch name on the go so it's not always Patch-4 by default to prevent potential overwrites of other patches. V/Mmap exporters usually read Patch-4 (sometimes up to 5) so it would be nice to be able to change the patch name.

**Comment by stoneharry** [comment]
v2.1.2 now has this feature. 😄 

https://github.com/stoneharry/WoW-Spell-Editor/releases

Closing.
