### ISSUE TITLE
Error #131 File corrupt on Spell.dbc

### ISSUE THREAD

**Issue by patrikpatrik** [stoneharry/WoW-Spell-Editor#192]
**Spell editor version**
SpellEditor_x64.exe
SpellEditor_x86.exe
Ladik's MPQEditor.exe
MyDbcEditor.exe
MyWarCraftStudio.exe

**Describe the bug**
Everytime I try to edit a Spell.dbc and repack it into an MPQ like patch-4.mpq or capitalized patch-4.MPQ, I always get this `Error #131 file corrupt on Spell.dbc` and I've tried everything. From using different dbc editors, to different MPQ unpack and repack resources. To saving the Spell.dbc separately into a temp folder, then renaming it back to Spell.dbc then repacking it. To opening patch-enUS-2.MPQ and modifying that directly, making sure the dbc file size is correct and all, still no go.

I'm using cmangos Wow client The Burning Crusade Version 2.4.3 and just cant seem to get it to patch. I've tried placing the mpq patch file in ./data folder and even in ./enUS out of desperation which most likely is pointless. 

Anyway, without any of these patches or dbc edits, cmangos works fine out the box with no modifications, and strangely when I try to modify `hearthstone` cooldown through the tbc mysql database that works!

All I wanted to do was change warrior's `Charge` range from 25yards to anywhere which is Column 41 value 95 to 13 respectively. I meticulously went through my `spell_template` table in `tbcmangos` database and updated those values accordingly, for Rank1 and all the others just to be safe. I've also updated Spell.dbc in the ./dbc folder on the server side, which I was told was unecessary but still did it. Then I was told that range values are done client side so I have to repack the mpq after editing Spell.dbc and thats where I'm getting this Error #131 File corrupt on Spell.dbc.

 I'm wondering if is it possibly all my dbc editors are wrong? Or maybe my wow 2.4.3 is bad? But if it works fine without ANY modifications... what could be the issue? Sorry for sounding so noobish but its been keeping me up for days now and I'm not sure what to do at this point. I wish I could simply change my warriors charge skill to be a lot farther from 25 yards, ive checked and rechecked the mysql rows to verify that, checked and rechecked Spell.dbc. 

On a sidenote I finally got your spell editor to work beautifully, it successfully exports Spell.dbc if I want or the full patch-4.mpq if I want. I've used yours to export, ive tried Ladik's to add and create mpq, ive tried myWarcraftStudio.exe version of its MPQ extracting and creating, ive reinstalled the wow client 2.4.3 freshly about 6 or 7 times now. Always restarted realmd + mangosd servers each time and most importantly deleted my cache folder each time to make sure nothing old is hanging around but still does this error pop up.

Edit - Lastly, running Windows 11 x64.

**Comment by patrikpatrik** [comment]
@stoneharry, please close this bug. The entire problem was a freakin wowme.exe that I simply had to run. This made all the `error #131` go away. Btw your spell editor works fantastic exports mpq and dbc perfectly and its way better than cross-referencing back and forth with other dbc editors/mpq editors out there. Thank you. Again works for cmangos tbc 2.4.3, just need to follow directions and spend countless sleepness nights and it WILL work. Cheers~

**Comment by stoneharry** [comment]
Glad you got it working.
