### ISSUE TITLE
ruRU DBC does not work

### ISSUE THREAD

**Issue by SQWIZI1337** [stoneharry/WoW-Spell-Editor#197]
**2.0.4**
Please provide the spell editor version you are using.

**Describe the bug**
ruRU DBC does not work.SPELL everything in English and description too

**Expected behavior**
see spell in Russian

**Screenshots**
![image](https://user-images.githubusercontent.com/114282670/224419637-2aefbb53-8823-40fc-ad59-659c7e1954ed.png)
![image](https://user-images.githubusercontent.com/114282670/224421170-b676732f-c05c-40d9-9c2d-fbe9f7b31e91.png)

**Comment by stoneharry** [comment]
Can you upload your ruRU DBC files for me to test with please? I will be on holiday for a week from tomorrow so may take a while to look into it.

**Comment by SQWIZI1337** [comment]
https://drive.google.com/file/d/15mXFw3Mf9Mh2n9caTTByMky_zn-fRp5b/view?usp=share_link

**Comment by stoneharry** [comment]
![Img](https://i.imgur.com/N1BJhXj.png)

Works for me, do you have the right folder configured? Just checking you know it requires other DBCs too like areatable/areagroup right?

**Comment by SQWIZI1337** [comment]
![image](https://user-images.githubusercontent.com/114282670/224506612-b7dace09-67a0-498a-b976-8e48f2d851ee.png)
I realized for some reason I can't import new files

**Comment by stoneharry** [comment]
You cannot import data once it is already imported. You need to click the 'drop tables' button to remove all existing data.

**Comment by SQWIZI1337** [comment]
thx
