### ISSUE TITLE
Clarity on wait for export 'loading' tables

### ISSUE THREAD

**Issue by shardic-er** [stoneharry/WoW-Spell-Editor#200]
The 'loading...' text next to dbc's in the export interface lacks visual clarity that all the selectable checkboxes are not 'ready' yet. 

Making the 'loading' text red, (i.e. Export\Spell.dbc) or adding some other visual indicator near 'Export Checked To MPQ' that not all selctable tables are ready would add clarity and prevent premptive exports. 

Additionally, a 'select all' button would be nice to select all available checks from the same interface.

One more minor thing:
It might also be a slight bit of QOL to be able to configure a directory for .MPQ's and .DBC's files that get exported to automatically get placed in, as an alternative to the 'exports' folder of the application, so that exported changes can be applied direclty to the game with less time copying files. Something like a filepath config for 'Client\DATA' and "bin\dbc"

**Comment by stoneharry** [comment]
Should be improved a lot under #208 but won't fix everything.

**Comment by stoneharry** [comment]
v2.1.2 now has this feature. 😄 

https://github.com/stoneharry/WoW-Spell-Editor/releases

**Comment by stoneharry** [comment]
I would recommend creating a symlink to automatically have the files in the required directories instead of the program needing that functionality. Going to close this as done.
