### ISSUE TITLE
Chang spell visual

### ISSUE THREAD

**Issue by cartilagecrush** [stoneharry/WoW-Spell-Editor#202]
Hi!

Is it possible to change the spell visual of Lesser healing wave to the visual of Riptide? I tried changing it through Missile model but that didn't work. Maybe I did something wrong?

Thanks!

**Comment by Sulan2** [comment]
Hi

In order to do this you have to change the value in Spell Visual 1 in Base Section.
Riptide ID is 12994 so just put that in Lesser healing waves spell visual 1.

This needs to be patched into MPQ file to be visual in the game aswell
