### ISSUE TITLE
What are the respective functions of "Misc Value A" and "Misc Value B"?

### ISSUE THREAD

**Issue by danqu** [stoneharry/WoW-Spell-Editor#203]
![image](https://github.com/stoneharry/WoW-Spell-Editor/assets/3050620/fbea489f-7cb9-4465-88d4-4e9f453680ef)

Could you please explain the respective functions of "Misc Value A" and "Misc Value B" in the SpellEditor tool? Thank you very much for your assistance.

**Comment by stoneharry** [comment]
They are generic fields that are used differently by every spell and aura effect.

There is a community maintained list here: https://github.com/stoneharry/WoW-Spell-Editor/issues/115

You can also refer to the emulator SpellEffects.cpp and SpellAuraEffects.cpp usage.
