### ISSUE TITLE
Faster Spell Duplication

### ISSUE THREAD

**Issue by Sulan2** [stoneharry/WoW-Spell-Editor#206]
Hey Harry, would love if it was possible to right click in the scroll area on a spell and choose "create new spell from this spell" and then just write the new spell ID of the new spell.

**Comment by stoneharry** [comment]
Yeah this should behave the same way as the visual tab where you can right click kits/effects to perform actions on them (copy / paste / delete / new) and each action should not refresh the entire spell list.

There is a fair bit of technical debt with the spell selection list. This is something that I have been meaning to do for a long time but I need to sit down with a few hours free time and the motivation to actually do it. :)

**Comment by stoneharry** [comment]
#213 Fixes this.

**Comment by stoneharry** [comment]
Fixed in release build v2.2.0.

**Comment by Sulan2** [comment]
Absolute game changer, thank you so much @stoneharry
