### ISSUE TITLE
Crash when using variables with multiple string characters

### ISSUE THREAD

**Issue by itswicky** [stoneharry/WoW-Spell-Editor#214]
**Spell editor version**
2.11

**Describe the bug**
There are some variables that have multiple letters, like $sp which will return an error when used in a formula and then loaded in the spell ingame description area. I.E. ${$sp * 50} because it will assume $s is the variable and then try and multiply a string, p, by an int.

**To Reproduce**
1. Edit the spell description of a spell and attempt to perform any math function with a variable that has more than one character. I.E. ${$SP * 2}.
2. The Ingame Description window will attempt to do math on a string character.
3. Error will occur and spell will be overwritten by the next spell you select.

**Expected behavior**
Spell Ingame Description window should instead know that any characters following a $ sign and preceding a space is calling a variable. Some variables are 3 characters long iirc.

**Screenshots**

**Additional context**

**Comment by stoneharry** [comment]
Should be fixed in v2.2.0.
