### ISSUE TITLE
Duplicating Spells Resetting Previously Duplicated Spellnames on the Spell Lists

### ISSUE THREAD

**Issue by KeatenStJ** [stoneharry/WoW-Spell-Editor#216]
**Spell editor version**
Please provide the spell editor version you are using.
Newest version 2.2.0

**Describe the bug**
When duplicating the spells. If i have duplicated a few, it resets the previously duplicated spells spell name on the lists of spells area, but it doesnt actually change the spellname of the spells. Just what shows where it shows all the spells. It only does it to previously duplicated spells. It is easily fixed by going over the spells that has had the change happen to and resaving. 

**To Reproduce**
1. Go to '...' Start duplicating spells and changing spell names
2. Click on '....' rinse and repeat
3. Scroll down to '....' will notice previously duplicated ones revert their display spell name, not their actual spell name

**Expected behavior**

**Screenshots**

**Additional context**
I can easily show on stream if that helps, #Keaten . Sorry im sure my explanation doesnt do a great job

**Comment by stoneharry** [comment]
Fixed with v.2.2.1.
