### ISSUE TITLE
Limit of spells

### ISSUE THREAD

**Issue by Lucillien05** [stoneharry/WoW-Spell-Editor#218]
**Spell editor version**
Newest 2.2.0

**Describe the bug**
When having multiple custom spells, there is limit, which is imported into spell editor (into mysql). When tried to import custom spell.dbc file, only a part of them is really imported, other part is totally ignored. I found out, only 50000 rows imported into mysql and into editor, so I guess this is where limit goes. I hope I can somehow change this limit?

**Comment by stoneharry** [comment]
There is no limit. Upload your DBC here and I can take a look, it's possible there is bad data such as duplicate ids that are throwing an error.

**Comment by Lucillien05** [comment]
> There is no limit. Upload your DBC here and I can take a look, it's possible there is bad data such as duplicate ids that are throwing an error.
![image](https://github.com/stoneharry/WoW-Spell-Editor/assets/109629766/47c68b4a-f117-4139-b320-408bc10fab9c)
yes, there are duplicates, so not editor's problem. Wouldn't you please have guesses, how it can be repaired? No duplicates are shown when exported into csv.

**Comment by Lucillien05** [comment]
Fixed
