### ISSUE TITLE
[Feature Revamp Request] Icon Loading Efficiency

### ISSUE THREAD

**Issue by howtokana** [stoneharry/WoW-Spell-Editor#228]
**Is your feature request related to a problem? Please describe.**
Adding additional icons to the spell editor will make it lag/freeze when loading icons if there is enough of them. 

**Describe the solution you'd like**
Would it be possible to take a look at how it's handled so it's logic is friendlier towards more icons?

**Any other comments/information**
If this is a tall order or requires too much work please don't pay this post any attention.

**Comment by stoneharry** [comment]
This is already implemented. Check the config.

![screenshot](https://i.imgur.com/QVosO51.png)

When 'render only icons in view' is enabled it will only load icons that are visible in the UI. This is slower to scroll up and down, but makes the program more performant with a large amount of icons.

Changing the config option requires a program restart to take effect.

**Comment by howtokana** [comment]
Didn't that know that was an option, thank you very much!
