### ISSUE TITLE
Can't import dbc

### ISSUE THREAD

**Issue by lalbok** [stoneharry/WoW-Spell-Editor#241]
I changed configs to vanilla, but when I'm trying to import dbc files window just closes down and when I'm opening the import tab this is what it sows. Any ideas how to fix this?
![image](https://github.com/user-attachments/assets/db01c685-abcc-4d50-8bb8-1e628da774c2)
![image](https://github.com/user-attachments/assets/20f7d78d-9b15-4804-bbe8-9bd5a36139d6)

**Comment by stoneharry** [comment]
You can check `error.txt` and `debug_output.txt` for errors.

Delete the MySQL database then try again.

**Comment by lalbok** [comment]
There is no error.txt, checked debug_output.txt there is no errors. Where can I find mysql database?

**Comment by stoneharry** [comment]
Try using SQLite instead of MySQL if you don't understand how MySQL works. It's easier. It will use `SpellEditor.db` file in same directory as spell editor.

**Comment by lalbok** [comment]
So there is no other way other then deleting mysql database or changing to sqlite? I have set up server to mysql so I guess I need to do everything in sqlite instead?

**Comment by stoneharry** [comment]
If you don't know how to drop a database from MySQL, simply go into the config and change the database name to something else.

**Comment by lalbok** [comment]
It gives me this 
![image](https://github.com/user-attachments/assets/8d287c88-3136-42aa-8f67-f8dee9065875)

**Comment by stoneharry** [comment]
You interact with MySQL with a IDE like SQLyog, Navicat, HediSQL, or MySQL Workbench. You do not try to edit data in Windows explorer, that will break it pretty badly. You can google on how to work with MySQL.

Again, go into the spell editor config and simply change the MySQL database name used to some new unique value.

**Comment by lalbok** [comment]
Got it, thanks a lot!

**Comment by stoneharry** [comment]
Is this fixed?

**Comment by lalbok** [comment]
Yeah yeah, thanks again
