### ISSUE TITLE
How to edit duration and stack size of a spell / Talent passive

### ISSUE THREAD

**Issue by JoeyCool11** [stoneharry/WoW-Spell-Editor#247]
Trying to get shadow weaving to stack up to 50 times and have a 5 minute duration. Attached screenshots of what I did so far, making sure this is right. 
It seems to have exported because I made a duplicate spell, used Gm command to learn it and now my Shadow Weaving stacks 2 times per spell cast, but it still only goes to 15 seconds and 5 total stacks.

![image](https://github.com/user-attachments/assets/6d5fcd0c-b110-4cb2-bb2a-c6460355a062)
![image](https://github.com/user-attachments/assets/018d7d88-1899-4c49-b5fc-0ac8e23b1414)

**Comment by stoneharry** [comment]
I think we solved this in the WoW modding Discord. Closing, but feel free to re-open if it is still an issue.
