### ISSUE TITLE
bad column

### ISSUE THREAD

**Issue by Sparco6** [stoneharry/WoW-Spell-Editor#28]
![image](https://cloud.githubusercontent.com/assets/8561511/19204590/e5c29cae-8cdd-11e6-82f2-74148b6fd13f.png)
Hi, i see this when i logged on my mysql Trinity Core server.. but i dont know how to fix it..

**Comment by stoneharry** [comment]
Sounds like you have set it to use the TrinityCore spell dbc table. This is not correct. The TrinityCore table does not include all of the columns that make up a spell dbc record. If you change the table name to something unique then it will create and import the data to that.

**Comment by Sparco6** [comment]
Hi, i import this https://github.com/Sarjuuk/dbcsql Spell.dbc sql but still i look on it and missing some column, i add it manual and then i say it.. still showing me the same problem as on pic up..

**Comment by stoneharry** [comment]
Thanks for providing the spell.dbc you are trying to use, I will test this tomorrow if you still cannot figure it out.

**Comment by Sparco6** [comment]
now i import my own spell.dbc on my server(newestTrinityCore3.3.5a) and his have 
Columns (232) but still dont have SpellName0 i try to add it manual..

**Comment by Sparco6** [comment]
still nothing and same error, or i get new error of spell that cannot be added in database.. can you post your spell database ? only build or something to get full function of this program..

**Comment by stoneharry** [comment]
What is this spell.dbc.sql you have provided? This is not generated by this program. You need to target the program at a table that does not exist. Then it will ask if you want to import the spell.dbc.

When it imports the spell.dbc it automatically creates the table structure and populates it with the data.

**Comment by Sparco6** [comment]
i find it on net.., i use import to my database but have errors.. 
when i dont have table..
> Table 'masterwowz.db_Spell_12340' doesn't exist
when i create table
> Unknown column 'SpellName0' in 'field list'

**Comment by stoneharry** [comment]
No: do not use random files from the Internet. 

This tool, a mysql server, and the spell Dbc is all you need. 

You can get the spell Dbc from your WoW client in the mpq files. 

You need to use the one from your client because it contains your language. I only have the English one. 

WoW editing tutorial : http://modcraft.superparanoid.de/viewtopic.php?f=78&t=3434

Use mpq editor to extract the Dbc.

**Comment by Sparco6** [comment]
i use my own dbc from my server.. but have error Unknown column 'SpellName0' in 'field list' and cannot copy 
![image](https://cloud.githubusercontent.com/assets/8561511/19361625/b93f3476-9183-11e6-823d-2a2a0ea1aa73.png)

![image](https://cloud.githubusercontent.com/assets/8561511/19361639/cd219d58-9183-11e6-935f-a926b455c7af.png)

This is Import
![image](https://cloud.githubusercontent.com/assets/8561511/19361690/f7e18fbc-9183-11e6-93f7-e95a3f263ef1.png)
and got this error.. and in database is only what i post.. and nothing changed..
![image](https://cloud.githubusercontent.com/assets/8561511/19361710/0df085ec-9184-11e6-9b6e-bc9dd9e05a16.png)

**Comment by stoneharry** [comment]
Can you upload your spell.dbc and I will try with it?

**Comment by Sparco6** [comment]
https://ufile.io/a2413

**Comment by Sparco6** [comment]
any news ? :)

**Comment by stoneharry** [comment]
I might have a chance to look at it this week - I'm not making any promises though. I will try to make time for it, there's a few bits of this project I want to update.

**Comment by Sparco6** [comment]
ok thanks. :)

**Comment by stoneharry** [comment]
I still haven't looked at this - sorry. Again, I will try to make time for it as soon as I can. It's rare I sit down at my computer and actually work on code these days.

**Comment by Sparco6** [comment]
ok no problem :)

**Comment by stoneharry** [comment]
Ah man, bad news. I went to look at this just now and the file link to your spell.dbc has expired. Can you reupload it? I have a bit of free time over the christmas period.

**Comment by Sparco6** [comment]
http://www.filedropper.com/spell here :)

**Comment by piehead** [comment]
I'm having the same issue as Sparco6. [Here is an imgur album displaying the issue.](http://imgur.com/a/v4KLT). I'm unsure what the issue is as I don't think its my spell.dbc file. I'm using an older version of your spell editor and that works just fine.

**Comment by stoneharry** [comment]
@piehead Are you using SQLite or MySQL connection types? And what locality are you using? enUS/enGB?

**Comment by piehead** [comment]
Interestingly when I extracted the Spell.dbc from my client using my MPQ editor I got the same error you just did @stoneharry. But when I used the one I had previously, I got the error I had earlier. attached is a .zip with my spell.dbc that got the error I mentioned in my previous post.

And to answer your questions. I am using enUS and using the MySQL connection.

[Spell.zip](https://github.com/stoneharry/Spell-Editor-GUI-V2/files/1203258/Spell.zip)

**Comment by stoneharry** [comment]
Okay, that imported fine using SQLite so it must be an issue with the MySQL code. I will setup a local server to test it.

http://i.imgur.com/jhjEPOC.png

**Comment by stoneharry** [comment]
That spell.dbc you provided has actually imported fine as well using MySQL:

http://i.imgur.com/SjcVtrb.png
http://i.imgur.com/TAvsWbs.png

Using this version of MySQL: http://i.imgur.com/XbxYWba.png

What MySQL version are you using?

**Comment by piehead** [comment]
I'm not 100% sure where to check this like you did. But I assume its 5.6.37.

Here is a screenshot of all the mysql stuff I have installed.
![mysql status](https://user-images.githubusercontent.com/5630669/29006784-8b1886bc-7ac4-11e7-9c2c-ce64450606a6.png)

**Comment by stoneharry** [comment]
Are you using the 32 or 64 bit version of the program? Did you copy the x64 SQLite.Interop.dll if using 64 bit? Have you tried using the other version to what you are using? It could be dependant on your MySQL server architecture.

If that still does not work then I will have a look at it this weekend hopefully. My first step would be to install the version and distribution of MySQL you are using.

**Comment by piehead** [comment]
I was using the 64 bit version and so I just tried the 32 bit even though I had copied the files over previously. That did not fix the issue. I can't say I understand what you mean by my server architecture however.

**Comment by stoneharry** [comment]
This is a very old issue and the program has changed a lot. Closing this assuming it is no longer a problem.

**Comment by Sparco6** [comment]
fixed :D

**Comment by Variona** [comment]
> fixed :D

Yes, it is no longer an issue.
