### ISSUE TITLE
Support for the localization of the interface

### ISSUE THREAD

**Issue by qyh214** [stoneharry/WoW-Spell-Editor#35]
Although we can clone it and modify it then compile to native language ,if provide a Interface maybe cool and well!~we can more convenient merge code.
for example you add a folder:/loc/ ,we put zhcn.js,zhtw.js(or zhcn.ini) .
in UI we can easy to change language.

**Comment by stoneharry** [comment]
I did not realise that there would actually be demand for this sort of feature. We have been discussing it partly in issue #33.

**Comment by Norbivar** [comment]
Runtime changing of XAML (GUI) element properties can be achieved, can it not? 
I am only guessing because I believe 'name' properties can be added to Labels and accessing them should be straightforward.
(Not really used this framework before)

**Comment by stoneharry** [comment]
Yes @Norbivar, it is a really simple thing to make translations work. But a lot of time is required to convert the entire interface and all the strings to use this new internationalisation system.

**Comment by Norbivar** [comment]
I might be able to spare some time @stoneharry, though the method of processing is still in question.

**Comment by stoneharry** [comment]
#73 should resolve this when it is merged.

**Comment by stoneharry** [comment]
Fixed in b9d8f7063e32c453f1c8be25af0500b0702207e5. This will be included in versions higher than v1.8.3.
