### ISSUE TITLE
Doesn't create table

### ISSUE THREAD

**Issue by Nightfall-WoW** [stoneharry/WoW-Spell-Editor#60]
It doesn't create the editing table but creates the database and all other tables, so its not an issue with the MySQL connection. Wouldnt be that big of an issue if I had the SQL Code for the table.

**Comment by stoneharry** [comment]
I do not fully understand what you describe as happening. What do you mean by the editing table?

What version are you using? Which locale DBC files are you using?

It generates the query to create the table at runtime based on the text bindings.

**Comment by Nightfall-WoW** [comment]
Well the one where it temporarily pastes in the queries to edit them I believe. I couldnt use your program yet as it wasn't able to create that one specific table.
I was using the most recent version at that time. 1.8.3 I believe
I was using enUS files I believe, or enGB

**Comment by stoneharry** [comment]
v1.8.3 has not been released at this time of writing. Perhaps your MySQL user does not have the correct permissions to create the table? It needs to be able to create a database called 'spell'. Use a new database with no tables, give the user standard permissions (insert, delete, select, update) and table creation.

There should be some debug text output in a file next to the program. You could paste that here to see if there any errors being reported.
