### ISSUE TITLE
v1.8.x You can't select what dbc you want to export after upgrading from old version

### ISSUE THREAD

**Issue by mmlTools** [stoneharry/WoW-Spell-Editor#63]
v1.8.1 You can't select what dbc you want to export
https://i.imgur.com/qBpGWug.jpg

If you close the selection window, program just freeze and crash

**Comment by stoneharry** [comment]
It should display like this when you have no tables imported currently to export. Did you upgrade from an older version? I suspect the program works because the spell table exists from an older version, but the other tables do not exist for some reason.

**Comment by mmlTools** [comment]
yes you are right i was using an old DB for it, it would be nice to have a notification about that

**Comment by stoneharry** [comment]
I am trying to reproduce this by dropping random MySQL tables then restarting the program and using the import/export window. I can't seem to. Because the issue was resolved for you by reimporting I'm not really going to put much more effort into trying to reproduce this.
