### ISSUE TITLE
Spell effects not updated in Effects 2

### ISSUE THREAD

**Issue by RikuAotsuki** [stoneharry/WoW-Spell-Editor#64]
I noticed this with effect 136, HEAL_PCT. On the Effects 1 tab, it's listed as such. On Effects 2,  it's "unknown_16." On further inspection, it looks like most of the effects listed as unknown in Effects 2 are listed with an actual name in Effects 1. I'm assuming the two parts need to be updated separately?

**Comment by stoneharry** [comment]
Thanks for the report. The effects1 tab duplicates fields on the effects2 tab, and you are right that they are inconsistent. They do update the same DBC value.

I have removed the duplicate fields on effects1 in 10ce8db. This will be available in v1.8.3 when it is released.

**Comment by stoneharry** [comment]
Released build v1.8.3 which includes this.
