### ISSUE TITLE
Error with using Health as PowerType

### ISSUE THREAD

**Issue by Makpptfox** [stoneharry/WoW-Spell-Editor#65]
When you set the PowerType of a spell to "Health" and save it, you're unable to load and thus edit it anymore. It also the case for Blizzard's spells using Health as Powertype.

To reproduce the error, simply open the SpellID **1454** in the editor.

I am using the lastest version of the Editor (1.8.2) in 64bits and have the French locale.

**Comment by stoneharry** [comment]
Thanks for the report, fixed in e269e32. This will be included in version v1.8.3 when it is released.

**Comment by stoneharry** [comment]
Released build v1.8.3 which includes this.
