### ISSUE TITLE
[QUESTION] What are dummy effects ?

### ISSUE THREAD

**Issue by ladiszlai** [stoneharry/WoW-Spell-Editor#67]
I am sorry for posting here, but I have searched the whole internet for this, but I couldn't find any information about it. I am wondering about "SPELL_EFFECT_DUMMY = 3" what this is for ? what is it doing exactly ?

**Comment by Makpptfox** [comment]
It is generally a "call" to a script stored in the table "spell_script_names", it is not the only use of it, but it is most likely the usage of Dummy effect.

i.e the SpellID _31852_ use the Dummy on its spell effect 2, which is used by the spell script named **spell_pal_ardent_defender** .

Somes use it to create a "display" spell, to simply set an aura on something/someone which give nothing but the icon in the auras bar.

**Comment by ladiszlai** [comment]
Thank you very much !! :)
