### ISSUE TITLE
on first startup, close the program on pressing cancel

### ISSUE THREAD

**Issue by mmlTools** [stoneharry/WoW-Spell-Editor#70]
When you first start up the program better add a closing event on canceling for example you write a wrong hostname or user and don't want to continue the setup process is a small thing but pretty annoying

**Comment by Makpptfox** [comment]
Pretty sure pressing "Esc" does that.

**Comment by mmlTools** [comment]
I guess this can be closed as you already added a config file is not worth wasting time on this

**Comment by mmlTools** [comment]
Fixed with the addition of the config file
