### ISSUE TITLE
program is not creating the database and table on first config

### ISSUE THREAD

**Issue by mmlTools** [stoneharry/WoW-Spell-Editor#71]
looks like the program create its own tables for example i named the table spells and the program named the table spell and it threw this error 
![image](https://user-images.githubusercontent.com/11877277/52916860-376c6780-32ed-11e9-8b32-533e9d699602.png)

after that program just stuck on loading dbc files and populating the ui and i can't close unless i kill the process.

After manually editing the config.xml it works

**Comment by stoneharry** [comment]
This has been the case since v1.8.0 which says: `All tables imported will be named the same as the DBC file.` The table name option needs to be removed completely.

**Comment by stoneharry** [comment]
The table option has been removed completely in b9d8f70 affecting versions greater than v1.8.3.
