### ISSUE TITLE
SpellEditor.Sources.Binding.BindingManager threw an exception

### ISSUE THREAD

**Issue by Persephone** [stoneharry/WoW-Spell-Editor#74]
Whenever i attempt to start the program this happends:

http://prntscr.com/movuzr

SpellEditor.Sources.Binding.BindingManager threw an exception

Is this a known issue or am i doing something wrong?

It happends on a fresh start after putting in what mysql informations i have. I am running it in debug mode on win 10 and using mysql server 5.6

the debug.txt file has this:

`######################################################
Starting WoW Spell Editor - 23-02-2019 00:42:54
######################################################
ERROR: The type initializer for 'SpellEditor.Sources.Binding.BindingManager' threw an exception.
`

**Comment by stoneharry** [comment]
You are trying to run it from visual studio and so you need to add the files for the program in the correct directory. You can set it up yourself or copy the files in from the latest release: https://github.com/stoneharry/WoW-Spell-Editor/releases

For me that path is: `Spell-Editor-GUI-V2\SpellGUIV2\bin\x64\Debug`

**Comment by Persephone** [comment]
The latest release refuses to compile for me though:

`Severity	Code	Description	Project	File	Line	Suppression State
Error		The "Fody.WeavingTask" task was not given a value for the required parameter "SolutionDir".	SpellEditor			
Error	CS0246	The type or namespace name 'MySql' could not be found (are you missing a using directive or an assembly reference?)	SpellVisualMapBuilder	C:\Users\Rasmu\Downloads\WoW-Spell-Editor-1.8.3\WoW-Spell-Editor-1.8.3\SpellVisualMapBuilder\Program.cs	8	Active
`

**Comment by Persephone** [comment]
Also i wasnt running it from visual studo but from the build folder and i did add in the dbc folder with dbc files etc, i was trying to run a debug instance within VS to try and find the cause but havent found anything yet

**Comment by Persephone** [comment]
@stoneharry Besides building SpellEditorV2 what files are you saying is nessecary to be in the build folder for it to run properly? because i keep getting that binding error

**Comment by Persephone** [comment]
Oh i see now, theres an extra folder in the new release. Where was i gonna get this information from? Its not in the readme (no hate i love your work, just a bit confused <3)

**Comment by Persephone** [comment]
I am able to get past that error now, with the downloaded and built version. But if i specify a table i want it to create it just says "Table 'spelleditor.spell.dbc' doesn't exist". And if i specify a table from an older version as a target, itll load up then just show like this:

Table 'spelleditor.spell.dbc' doesn't exist

any ideas what i am doing wrong?

**Comment by Persephone** [comment]
Nvm lol figured it out! thanks harry

**Comment by stoneharry** [comment]
It would be handy to post what you were doing wrong so that other people can see if they encounter this issue.

**Comment by Persephone** [comment]
I was unaware that i needed extra folders like the Bindings folder, as simply cloning the source and compiling it doesnt give any and the readme does not tell about it as well. So i couldnt get the program to run as i had missing files that i was unaware of were missing, dunno if i am just stupid or the readme has to be updated :P anyway, it works now and i love the program harry!

**Comment by stoneharry** [comment]
The readme needs to be updated. 👍
