### ISSUE TITLE
Spell effect type names are wrong in Effects 2

### ISSUE THREAD

**Issue by TheHighlord** [stoneharry/WoW-Spell-Editor#80]
https://github.com/stoneharry/WoW-Spell-Editor/issues/64

In the Effects 1 tab the effect names were correct. Instead of updating the names from Effects 1 to Effects 2, you just deleted the effects type from Effects 1 tab.
For example effect 42 says "SUMMON_GUARDIAN", but that is "SPELL_EFFECT_JUMP_DEST". 

Can you fix it please ? :)

**Comment by stoneharry** [comment]
I'll hopefully have time to look at this tomorrow.

**Comment by stoneharry** [comment]
Finally had a chance to look at this. It's been a while. 😅 Should be corrected in aed8fc7.
