### ISSUE TITLE
Multiple Value: 4

### ISSUE THREAD

**Issue by browller** [stoneharry/WoW-Spell-Editor#81]
Sometimes, this value keep saving on that effect and can't be reseted, i tried put 0, save spell and reload, and it was 4 again

**Comment by stoneharry** [comment]
'Sometimes' is hard to reproduce. :) If you are able to reproduce with an exact set of steps I can try to follow them to replicate. I'll have a go either way at reproducing this when I get a chance.

**Comment by stoneharry** [comment]
This may well be fixed in #121 which will be included in the next release.
