### ISSUE TITLE
can i get your library of importing/exporting into DBC and Mysql?

### ISSUE THREAD

**Issue by Dokman** [stoneharry/WoW-Spell-Editor#83]
so what the title says, i have another project that i want to start and i think your library is too good and i will try to implement some things

**Comment by stoneharry** [comment]
Feel free to use this project as a library or copy some of the DBC code. My question would be: what are you trying to do? The code in this project is far from perfect but I'm wondering if we can enhance this tool rather than start something new.

**Comment by Dokman** [comment]
I al wondering to make a character enhancer, and that's cause i think that your dbc library is way verter than anything that i can do hahahaha
