### ISSUE TITLE
"Input string was not in a correct format" when trying to load any rank of Serpent Sting

### ISSUE THREAD

**Issue by Mecar1997** [stoneharry/WoW-Spell-Editor#84]
The editor refuses to load any rank of Serpent Sting so I can't edit them.
I am using the latest rel version with clean .dbc files extracted with the extractor.bat file provided by Trinitycore

**Comment by stoneharry** [comment]
Sorry I've only just seen this report.

Which version are you using? v1.9.1 I can load these spells fine:

[13551 - Sepent Sting](https://i.imgur.com/XErUWK1.png)

**Comment by stoneharry** [comment]
Closing this because it was likely fixed since being reported. Please feel free to reopen this if you can reproduce it on the latest version (1.9.1 as I post this).
