### ISSUE TITLE
Unable to create tables in remote mariaDB server

### ISSUE THREAD

**Issue by c0ldrudi** [stoneharry/WoW-Spell-Editor#88]
When trying to use a MySQL (mariaDB) server as the spell DB, I get this error:

![toobig](https://user-images.githubusercontent.com/9332642/72670167-a0e38180-3a3a-11ea-8826-a0d2a754be09.png)

I attempted creating the Spell table from scratch with only text columns, but this results in very long loading times (10 minutes or more) and then it says no spells loaded. I am however able to create and delete spells, but not edit them.

Any idea how to fix this error?

**Comment by stoneharry** [comment]
Sorry I completely forgot to reply to this.

This application does not support mariadb at the moment. I can add support in a future update but I don't see it as a high priority. Why are you running mariadb? I don't know of any emulator that supports clustering well.

**Comment by c0ldrudi** [comment]
That makes sense then. I'm using Trinitycore 3.3.5 and it works without a hitch. I'll try to use regular MySQL instead. Thanks for the help and feel free to close this issue if you wish. :)

**Comment by stoneharry** [comment]
I'll leave this open to track adding support. :) It should be quite quick to implement but I'm on holiday at the moment.

**Comment by stoneharry** [comment]
I did some reading on the issue: https://stackoverflow.com/questions/15585602/change-limit-for-mysql-row-size-too-large

It looks like the fix is very simple. Tested and fixed in: 0a8a1d51c8804c6dbe13fb1fc8c76d581fa195b5

I will leave this issue open until a new release is published.

**Comment by stoneharry** [comment]
Fixed in v1.9.2.
