### ISSUE TITLE
Forgot to include SpellVisualMapBuilder in v1.9.2

### ISSUE THREAD

**Issue by Techwizz-somboo** [stoneharry/WoW-Spell-Editor#92]
Simply forgot to include that, no big deal. Just more of a fyi type of thing.

**Comment by Techwizz-somboo** [comment]
Oh and also how do I use it anyway? I got it from your previous build but I'm not sure how to get it to work.
I notice 4 files,
Creature.sql,
CreatureDisplayInfo.dbc,
CreatureModelData.dbc,
CreatureTemplate.sql.
Thanks so much and the program looks absolutely amazing!!

**Comment by stoneharry** [comment]
Thanks for pointing this out. I will include it again with the next update.

I need to update it to be more dynamic. It's all hardcoded at the moment.

https://github.com/stoneharry/WoW-Spell-Editor/blob/master/SpellVisualMapBuilder/Program.cs#L24

```c#
        // New DBC index to start from
        private static UInt32 DBCStartingEntry = 50000;
        // New Creature starting index
        private static UInt32 CTStartingEntry = 150000;
        // Map to spawn them on
        private static UInt32 MapEntry = 13;
        // Top left cell, both cells make a region it spawns in
        private static Int32[] MapTopLeft = { 138, 138 };
        // Bottom right cell, both cells make a region it spawns in
        private static Int32[] MapBottomRight = { -138, -138 };
        // Z coordinate, hardcoded to spawn at the same height
        private static Int32 MapZ = -144;
        // Size of each cell, 7x7
        private static Int32 CellSize = 7;
```

The SQL structure is also hardcoded: https://github.com/stoneharry/WoW-Spell-Editor/blob/master/SpellVisualMapBuilder/Program.cs#L100

You will need to add/remove any column changes with newer versions of TrinityCore.

Running it from command prompt should give you good debug output. The program needs the required DBC files and the SPELLS folder extracted from the client.

**Comment by Techwizz-somboo** [comment]
Awesome thanks Stoneharry! I love all the projects you've done!

**Comment by stoneharry** [comment]
Release build v1.9.3 has been published and contains this. Closing this issue.
