### ISSUE TITLE
Search existing spell's effects.

### ISSUE THREAD

**Issue by syama108** [stoneharry/WoW-Spell-Editor#93]
I often don't know how to use a spell effect so I search for other spells that use the said effect to understand.

**Describe the solution you'd like**
Possibly a search option to filter spells that use a certain spell effect.

**Comment by stoneharry** [comment]
Added in commit: 1b905b5902bc9a4ff3913e92cb9195126787bf53

![screenshot](https://i.imgur.com/gZ0yykj.png)

**Comment by syama108** [comment]
Mate, you're a badass. Cheers.

**Comment by stoneharry** [comment]
Release build v1.9.3 has been published and contains this. Closing this issue.
