### ISSUE TITLE
Application crashes when failing to load certain DBC

### ISSUE THREAD

**Issue by mmlTools** [stoneharry/WoW-Spell-Editor#94]
**Spell editor version**
Latest version 1.9.2

**Describe the bug**
Launched the app, tried to import all DEFAULT DBC files, when loading SkillRaceClassInfo.dbc it thrown an error, "DUPLICATED ID" and freeze
 
**To Reproduce**
1. Launch the program witouth having a database created
2. Click on import
3. Select all DBC files

**Expected behavior**
App should either pass and continue with the other files or close the import and try to clear the table

**Screenshots**
https://imgur.com/rtiBYN4

**Comment by stoneharry** [comment]
Thanks for the report.

I tried to reproduce this, but for me when failing to load a DBC file it doesn't crash the application:

!(screenshot)[https://i.imgur.com/n1E4FsL.png]

Is it possible you can attach your debug_output.txt please?

**Comment by stoneharry** [comment]
I managed to reproduce a NullPointerException dropping all tables then importing every DBC. The spell icon DBC was not in memory and so all spell icons fail to load, and presumably have other impacts I did not see.

This is now fixed in 3de8b99783f427e6a455cec06796b99e243f8028.

**Comment by stoneharry** [comment]
I think this has been resolved in v1.9.3. I am closing this issue for now, but feel free to open it again and comment if still encountering this.
