### ISSUE TITLE
Filter by name does not work if you start typing with capital letter

### ISSUE THREAD

**Issue by mmlTools** [stoneharry/WoW-Spell-Editor#95]
**Spell editor version**
Latest version 1.9.2

**Describe the bug**
If you write a spell name starting with capital letter in "Filter by name" no results are showing up in the list 

**To Reproduce**
1. Go to Filter By Name
2. Paste or start typing "Horn of Winter"
4. Nothing shows up in the list 
3. Start typing "horn of winter" with lowercase h, the results are showing up

**Expected behavior**
Application should search by either strtoupper or strtolower the whole name 

**Screenshots**
https://imgur.com/PlnQkXd
https://imgur.com/urS6BGQ

**Comment by stoneharry** [comment]
Fixed in 0e46f9e. I will leave this open until a new release is published that contains the fix.

Thanks for the report!

**Comment by stoneharry** [comment]
Release build v1.9.3 has been published and contains this. Closing this issue.
