### ISSUE TITLE
Spell duration converted to full times.

### ISSUE THREAD

**Issue by Elarose** [stoneharry/WoW-Spell-Editor#97]
Having the Duration dropdown list converted into the final outcome times in Hours, Minutes and Seconds, vs it being in Milliseconds.
![screenshot_420](https://user-images.githubusercontent.com/1474028/76266735-5652e880-62b8-11ea-8c60-657c9892f6ae.jpg)

**Comment by stoneharry** [comment]
How about this sort of approach?

!(screenshot)[https://i.imgur.com/CtSV25n.png]

I'm going to have to do some tweaking of the UI layout to make it fit in there, but it has been in need of a overhaul for a while.

**Comment by Elarose** [comment]
Lovely! =)

**Comment by stoneharry** [comment]
Some refactoring of the layout later:

!(screenshot)[https://i.imgur.com/U2GdNKf.png]

**Comment by stoneharry** [comment]
Committed enhancements in two commits:
- 00e9907f1a95341dd2a0ebdf716a5bb349182bfb
- 05a807123cb27c8947db67990a0237388146107a

These will be included in the next release. I will leave this issue open until then.

**Comment by stoneharry** [comment]
Release build v1.9.3 has been published and contains this. Closing this issue.
